# Generated by Django 2.1 on 2019-04-02 17:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FileLabel',
            fields=[
                ('fileLabel', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('introduction', models.TextField(max_length=500)),
                ('content', models.FileField(upload_to='files')),
                ('create_date', models.DateField(default=datetime.datetime(2019, 4, 2, 17, 55, 7, 285919))),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('fileLabel', models.ManyToManyField(through='upload_files.Associated', to='upload_files.FileLabel')),
                ('fileType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='upload_files.FileType')),
            ],
        ),
        migrations.AddField(
            model_name='associated',
            name='FileLabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.FileLabel'),
        ),
        migrations.AddField(
            model_name='associated',
            name='file_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload_files.UploadFiles'),
        ),
    ]
