# Generated by Django 2.1 on 2019-04-02 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0002_remove_uploadfiles_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
