# Generated by Django 2.1 on 2019-04-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0003_uploadfiles_create_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='icon',
            field=models.ImageField(blank=True, upload_to='files'),
        ),
    ]
