# Generated by Django 2.1 on 2019-04-10 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0004_uploadfiles_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='create_time',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
