# Generated by Django 2.1 on 2019-04-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0005_auto_20190410_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='fileLabel',
        ),
    ]
