# Generated by Django 2.1 on 2019-04-10 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0006_remove_uploadfiles_filelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
