# Generated by Django 2.1 on 2019-04-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0007_auto_20190410_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='fileType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='upload_files.FileType'),
        ),
    ]
