# Generated by Django 2.1 on 2019-04-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0008_auto_20190410_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='fileLabel',
            field=models.ManyToManyField(through='upload_files.Associated', to='upload_files.FileLabel'),
        ),
    ]
