# Generated by Django 2.1 on 2019-04-10 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0009_uploadfiles_filelabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='FileLabel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_files.FileLabel'),
        ),
        migrations.AlterField(
            model_name='associated',
            name='file_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='upload_files.UploadFiles'),
        ),
    ]
