# Generated by Django 2.1 on 2019-04-10 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0010_auto_20190410_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='create_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
