# Generated by Django 2.1 on 2019-04-11 01:37

from django.db import migrations, models
import django.db.models.deletion
import upload_files.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0011_auto_20190410_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associated',
            name='file_on',
            field=models.ForeignKey(default=upload_files.models.FileFieldDefault, on_delete=django.db.models.deletion.CASCADE, to='upload_files.UploadFiles'),
        ),
    ]
