# Generated by Django 2.1 on 2019-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0013_auto_20190417_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='is_active',
            field=models.SmallIntegerField(default=0),
        ),
    ]
